--테이블 간 관계 맺기-조인

--내부조인
SELECT *
FROM EMPLOYEES;

SELECT *
FROM DEPARTMENTS;

SELECT A.EMPLOYEE_ID,
       A.FIRST_NAME,
       A.DEPARTMENT_ID,
       B.DEPARTMENT_NAME
FROM EMPLOYEES A,
     DEPARTMENTS B
WHERE A.DEPARTMENT_ID=B.DEPARTMENT_ID
ORDER BY A.EMPLOYEE_ID;

--178번 사원은 조회가 안됨

SELECT A.EMPLOYEE_ID,
       A.FIRST_NAME,
       A.DEPARTMENT_ID
FROM EMPLOYEES A
WHERE A.DEPARTMENT_ID IS NULL
ORDER BY A.EMPLOYEE_ID;

--
SELECT A.EMPLOYEE_ID,A.FIRST_NAME||''||A.LAST_NAME,A.JOB_ID,B.JOB_TITLE
FROM EMPLOYEES A, JOBS B
WHERE a.JOB_ID=b.job_id
ORDER BY A.EMPLOYEE_ID;
--

SELECT A.EMPLOYEE_ID,A.FIRST_NAME||''||A.LAST_NAME,B.JOB_ID,B.JOB_TITLE,C.DEPARTMENT_ID,C.DEPARTMENT_NAME
FROM EMPLOYEES A, JOBS B, DEPARTMENTS C
WHERE A.DEPARTMENT_ID=C.DEPARTMENT_ID
AND    B.JOB_ID=A.JOB_ID
ORDER BY 1;

--

SELECT A.EMPLOYEE_ID,A.FIRST_NAME||''||A.LAST_NAME,A.JOB_ID,A.DEPARTMENT_ID,B.JOB_TITLE,C.DEPARTMENT_NAME,C.LOCATION_ID,D.STATE_PROVINCE,D.CITY,D.STREET_ADDRESS
FROM EMPLOYEES A,
     JOBS B,
     DEPARTMENTS C,
     LOCATIONS D
WHERE A.DEPARTMENT_ID=C.DEPARTMENT_ID
AND   A.JOB_ID=B.JOB_ID
AND   C.LOCATION_ID=D.LOCATION_ID
ORDER BY 1;

--외부조인

SELECT A.EMPLOYEE_ID, A.DEPARTMENT_ID, B.DEPARTMENT_ID, B.DEPARTMENT_NAME
FROM EMPLOYEES A, DEPARTMENTS B
WHERE A.DEPARTMENT_ID=B.DEPARTMENT_ID(+)
ORDER BY 1;
--A 테이블에 만족하지 않는 것을 조회하므로 178 번 사원도 조회가 된다.

SELECT A.EMPLOYEE_ID, A.DEPARTMENT_ID, B.DEPARTMENT_ID, B.DEPARTMENT_NAME
FROM EMPLOYEES A, DEPARTMENTS B
WHERE A.DEPARTMENT_ID(+)=B.DEPARTMENT_ID
ORDER BY 1;
--B 테이블에 만족하지 않는 것을 조회하므로 178 번 사원도 조회가 안된다.



SELECT A.EMPLOYEE_ID, A.FIRST_NAME||''||A.LAST_NAME,B.DEPARTMENT_ID,B.DEPARTMENT_NAME
FROM EMPLOYEES A, DEPARTMENTS B
WHERE A.DEPARTMENT_ID=B.DEPARTMENT_ID(+)
ORDER BY 1;
--A 테이블에 만족하지 않는 것을 조회하므로 178 번 사원도 조회가 된다.



SELECT A.EMPLOYEE_ID, A.FIRST_NAME||''||A.LAST_NAME,B.DEPARTMENT_ID,B.DEPARTMENT_NAME
FROM EMPLOYEES A, DEPARTMENTS B
WHERE A.DEPARTMENT_ID(+)=B.DEPARTMENT_ID
ORDER BY 1;
--B 테이블에 만족하지 않는 것을 조회하므로 178 번 사원도 조회가 안된다.