--TABLE 생성
CREATE TABLE EMP(
EMP_NO VARCHAR2(30) NOT NULL,
EMP_NAME VARCHAR2(100) NOT NULL,
SALARY NUMBER NULL,
HIRE_DATE DATE NULL);

DESC EMP;

--TABLE 조회
SELECT *
FROM EMP;

/*이것은 주석처리이다.*/ 

--TABLE 수정
ALTER TABLE EMP
MODIFY EMP_NAME VARCHAR2(80);

DESC EMP;

--TABLE 추가
ALTER TABLE EMP
ADD EMP_NAME2 VARCHAR2(80);

DESC EMP;

--TABLE 수정
ALTER TABLE EMP
RENAME COLUMN EMP_NAME2
         TO EMP_NAME3;

DESC EMP;

--TABLE COLUMN 삭제
ALTER TABLE EMP
DROP COLUMN EMP_NAME3;

DESC EMP;

--TABLE 추가
DROP TABLE EMP;

--TABLE 생성, PRIMARY KEY
CREATE TABLE EMP(
EMP_NO VARCHAR2(80) PRIMARY KEY,
EMP_NAME VARCHAR2(80) NOT NULL,
SALARY NUMBER NULL,
HIRE_DATE DATE NULL);

--TABLE 생성, PRIMARY KEY
CREATE TABLE EMP2(
EMP_NO VARCHAR2(80),
EMP_NAME VARCHAR2(80) NOT NULL,
SALARY NUMBER NULL,
HIRE_DATE DATE NULL,
PRIMARY KEY(EMP_NO));

--TABLE 생성, PRIMARY KEY
CREATE TABLE EMP3(
EMP_NO VARCHAR2(30),
EMP_NAME VARCHAR2(80) NOT NULL,
SALARY NUMBER NULL,
HIRE_DATE DATE NULL);

ALTER TABLE EMP3
ADD CONSTRAINTS EMP3_PK /*키값 이름*/ PRIMARY KEY(EMP_NO);

--SELECT문

/*SELECT 컬럼~
FROM 테이블명
WHERE 조건
ORDER BY 정렬순서;*/

DESC EMPLOYEES;

SELECT *
FROM DEPARTMENTS;

--100번인 사원 조회
SELECT *
FROM EMPLOYEES
WHERE employee_id = 100;

--100번이 아닌 사원 조회
SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID <>100; 

--100번이 아닌 사원 조회
SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID !=100; 

--사번이 100보다 크고 JOB_ID가 ST_CLERK인 사원조회
SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID >100 AND JOB_ID='ST_CLERK';

--급여가 5000이상이 사원 조회
SELECT *
FROM EMPLOYEES
WHERE SALARY>=5000;

--급여가 5000이상인 사원의 사번과 이름 급여를 조회
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY
FROM EMPLOYEES
WHERE SALARY>=5000;

--ORDER BY 
--사번순으로 정렬
SELECT *
FROM EMPLOYEES
ORDER BY EMPLOYEE_ID;

--사번순으로 내림차순 정렬
SELECT *
FROM EMPLOYEES
ORDER BY EMPLOYEE_ID DESC;

--이름 성순으로 오름차순 정렬
SELECT *
FROM EMPLOYEES
ORDER BY FIRST_NAME, LAST_NAME;

--이름 오름차순, 성 내림차순 정렬

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME
FROM EMPLOYEES
ORDER BY FIRST_NAME,LAST_NAME DESC;

--사원의 사번과 이름, 급여를 급여가 5000이상인 급여가 높은 순서로 조회
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY>--=5000
ORDER BY SALARY DESC;

--숫자를 명시해서 정렬 가능함
SELECT *
FROM EMPLOYEES;

SELECT *
FROM EMPLOYEES
ORDER BY 2,3 DESC; --2번째와 3번째 열을 중심으로 정렬

--ORDER_BY NULL정렬 방법 1) NULLS FIRST 2)NULLS LAST

SELECT EMPLOYEE_ID, FIRST_NAME,LAST_NAME,COMMISSION_PCT
FROM EMPLOYEES
ORDER BY COMMISSION_PCT NULLS FIRST;

--SQL 연산자
SELECT 1+1 PLUS_TEST, 1-1 MINUS_TEST
FROM DUAL;

--SQL 문자열 결합 1
SELECT 'A' || 'B' ||  'C'
FROM DUAL;

--SQL 문자열 결합 2
SELECT 'A' || '-' || 'B' || '-' || 'C'
FROM DUAL;

--SQL 비교 연산자
SELECT *
FROM EMPLOYEES
WHERE SALARY BETWEEN 3000 AND 5000
ORDER BY SALARY;

--SQL 비교 연산자
SELECT *
FROM EMPLOYEES
WHERE NOT(SALARY=2500)
ORDER BY SALARY;

--SQL 기타 연산자
    /* 
    (IS NULL, IS NOT NULL)
    LIKE '%D'
    LIKE 'D%'
    LIKE '%D%'
    컬럼I IN ( 값123)
    */
SELECT *
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NULL;

SELECT *
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL;

SELECT *
FROM EMPLOYEES
WHERE PHONE_NUMBER LIKE '011%';

SELECT *
FROM EMPLOYEES
WHERE PHONE_NUMBER LIKE '%124%';

SELECT *
FROM EMPLOYEES
WHERE JOB_ID IN ('IT_PROG','AD_VP','FI_ACCOUNT');

SELECT *
FROM EMPLOYEES
WHERE JOB_ID NOT IN ('IT_PROG','AD_VP','FI_ACCOUNT');

--CASE문 단순형, 검색형

SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY,JOB_ID
    ,CASE WHEN SALARY BETWEEN 1 AND 5000 THEN '낮음'
          WHEN SALARY BETWEEN 5001 AND 10000 THEN '중간'
           WHEN SALARY BETWEEN 10000 AND 15000 THEN '높음'
           ELSE '최상위'
           END SALARY_RANK
    FROM EMPLOYEES;
