--CTE와 SQL 처리과정

--WITH절 OR CTE

WITH DEPT AS(SELECT DEPARTMENT_ID,DEPARTMENT_NAME DEPT_NAME FROM DEPARTMENTS)
SELECT A.EMPLOYEE_ID,A.FIRST_NAME||''||A.LAST_NAME 
FROM EMPLOYEES A, DEPT B
WHERE A.DEPARTMENT_ID=B.DEPARTMENT_ID
ORDER BY 1;
-- 위에서 부터 순서대로 입력

WITH COUN_SAL AS(
SELECT C.COUNTRY_ID,SUM(A.SALARY) SAL_AMT
FROM EMPLOYEES A, DEPARTMENTS B, LOCATIONS C
WHERE A.DEPARTMENT_ID=B.DEPARTMENT_ID
AND B.LOCATION_ID=C.LOCATION_ID
GROUP BY C.COUNTRY_ID), 
    MAINS AS(
SELECT B.COUNTRY_NAME, A.SAL_AMT
FROM COUN_SAL A, COUNTRIES B
WHERE A.COUNTRY_ID=B.COUNTRY_ID)
SELECT *
FROM MAINS;

--과도한 WITH절 사용시 성능에 좋지않다

--TOP 5 QUERY
--ROWNUM
SELECT *
FROM (SELECT A.EMPLOYEE_ID, A.FIRST_NAME||''||A.LAST_NAME EMP_NAME, A.SALARY 
FROM EMPLOYEES A 
ORDER BY A.SALARY DESC)B
WHERE ROWNUM<=5;

--ROW_NUMBER
SELECT *
FROM (SELECT A.EMPLOYEE_ID, A.FIRST_NAME||''||A.LAST_NAME EMP_NAME, A.SALARY, ROW_NUMBER()OVER(ORDER BY A.SALARY DESC) ROW_SEQ
FROM EMPLOYEES A )
WHERE ROW_SEQ<=5;

--FETCH FIRST ROWS
SELECT A.EMPLOYEE_ID, A.FIRST_NAME||''||A.LAST_NAME EMP_NAME, A.SALARY
FROM EMPLOYEES A
ORDER BY A.SALARY DESC
FETCH FIRST 5ROWS ONLY;

--ORDER BY를 하지않으면 임의로 5개 로우가 조회됨
SELECT A.EMPLOYEE_ID, A.FIRST_NAME||''||A.LAST_NAME EMP_NAME, A.SALARY
FROM EMPLOYEES A
FETCH FIRST 5ROWS ONLY;

--PERCENT를 사용해 5%에 해당하는 로우를 조회
SELECT A.EMPLOYEE_ID, A.FIRST_NAME||''||A.LAST_NAME EMP_NAME, A.SALARY
FROM EMPLOYEES A
ORDER BY A.SALARY
FETCH FIRST 5 PERCENT ROWS ONLY;

--WITH TIES는 급여가 같은 값을 모두 조회, ONLY를 제거해줘야 된다.
SELECT A.EMPLOYEE_ID, A.FIRST_NAME||''||A.LAST_NAME EMP_NAME, A.SALARY
FROM EMPLOYEES A
ORDER BY A.SALARY
FETCH FIRST 5 PERCENT ROWS WITH TIES;