--ANSI 조인
--내부조인: INNER JOIN
--외부조인: LEFT OUTER JOIN, RIGHT OUTER JOIN, FULL OUTER JOIN

--ANSI 내부조인
SELECT A.EMPLOYEE_ID,
       A.FIRST_NAME,
       A.DEPARTMENT_ID,
       B.DEPARTMENT_NAME
FROM EMPLOYEES A
INNER JOIN DEPARTMENTS B
ON  A.DEPARTMENT_ID=B.DEPARTMENT_ID
ORDER BY A.EMPLOYEE_ID;

--ANSI 외부조인 
SELECT A.EMPLOYEE_ID,
       A.DEPARTMENT_ID,
       B.DEPARTMENT_ID,
       B.DEPARTMENT_NAME
FROM EMPLOYEES A
LEFT OUTER JOIN DEPARTMENTS B
ON A.DEPARTMENT_ID=B.DEPARTMENT_ID
ORDER BY 1;
--A만족하지 않는 178번 사원 조회'

SELECT A.EMPLOYEE_ID,
       A.DEPARTMENT_ID,
       B.DEPARTMENT_ID,
       B.DEPARTMENT_NAME
FROM EMPLOYEES A
RIGHT OUTER JOIN DEPARTMENTS B
ON A.DEPARTMENT_ID=B.DEPARTMENT_ID
ORDER BY 1;
-- B에 만족하지않는 모든 값도 다 조회, 즉 A의 178번 사원은 조회가 되지 않는다.

SELECT A.EMPLOYEE_ID,
       A.DEPARTMENT_ID,
       B.DEPARTMENT_ID,
       B.DEPARTMENT_NAME
FROM EMPLOYEES A
FULL OUTER JOIN DEPARTMENTS B
ON A.DEPARTMENT_ID=B.DEPARTMENT_ID
ORDER BY 1;
--178번 사원과 B테이블에서 만족하지않는 것들도 다 조회가 된다.

SELECT A.EMPLOYEE_ID,
       A.FIRST_NAME||''||A.LAST_NAME,
       A.JOB_ID,
       B.JOB_ID,
       B.JOB_TITLE,
       C.DEPARTMENT_ID,
       C.DEPARTMENT_NAME
FROM EMPLOYEES A
INNER JOIN DEPARTMENTS C
ON A.DEPARTMENT_ID=C.DEPARTMENT_ID
INNER JOIN JOBS B
ON B.JOB_ID=A.JOB_ID
ORDER BY 1;

--
SELECT A.EMPLOYEE_ID,
       A.FIRST_NAME||''||A.LAST_NAME,
       A.JOB_ID,
       B.JOB_ID,
       B.JOB_TITLE,
       C.DEPARTMENT_ID,
       C.DEPARTMENT_NAME
FROM EMPLOYEES A
LEFT JOIN DEPARTMENTS C
ON A.DEPARTMENT_ID=C.DEPARTMENT_ID
INNER JOIN JOBS B
ON A.JOB_ID=B.JOB_ID
ORDER BY 1;
--
SELECT A.EMPLOYEE_ID,
       A.FIRST_NAME||''||A.LAST_NAME,
       A.JOB_ID,
       B.JOB_ID,
       B.JOB_TITLE,
       C.DEPARTMENT_ID,
       C.DEPARTMENT_NAME
FROM EMPLOYEES A
LEFT JOIN DEPARTMENTS C
ON A.DEPARTMENT_ID=C.DEPARTMENT_ID
INNER JOIN JOBS B
ON A.JOB_ID=B.JOB_ID
ORDER BY 1;

--178Q번 조회 왜냐하면 JOB_ID는 NULL값이 아니기 떄문에


SELECT A.EMPLOYEE_ID,A.FIRST_NAME||''||A.LAST_NAME,A.DEPARTMENT_ID,C.DEPARTMENT_NAME,C.LOCATION_ID,D.STATE_PROVINCE,D.CITY,D.STREET_ADDRESS
FROM EMPLOYEES A
LEFT JOIN DEPARTMENTS C
ON A.DEPARTMENT_ID=C.DEPARTMENT_ID
INNER JOIN LOCATIONS D
ON   C.LOCATION_ID=D.LOCATION_ID
ORDER BY 1;
--178번 사원 조회 안됨

--


SELECT A.EMPLOYEE_ID,A.FIRST_NAME||''||A.LAST_NAME,A.DEPARTMENT_ID,C.DEPARTMENT_NAME,C.LOCATION_ID,D.STATE_PROVINCE,D.CITY,D.STREET_ADDRESS
FROM EMPLOYEES A
LEFT JOIN DEPARTMENTS C
ON A.DEPARTMENT_ID=C.DEPARTMENT_ID 
LEFT JOIN LOCATIONS D
ON   C.LOCATION_ID=D.LOCATION_ID 
ORDER BY 1;
--178번 사원 조회


----------CARTESIAN PRODUCT

SELECT *
FROM DEPARTMENTS;

SELECT A.REGION_NAME, B.DEPARTMENT_ID, B.DEPARTMENT_NAME
FROM REGIONS A, DEPARTMENTS B
WHERE 1=1;


----셀프조인: 동일한 테이블 끼리 조인
SELECT A.EMPLOYEE_ID, A.FIRST_NAME||''||A.LAST_NAME, A.MANAGER_ID,B.FIRST_NAME||''||B.LAST_NAME
FROM EMPLOYEES A, EMPLOYEES B
WHERE A.MANAGER_ID=B.EMPLOYEE_ID
ORDER BY 1;

SELECT A.EMPLOYEE_ID, A.FIRST_NAME||''||A.LAST_NAME, A.MANAGER_ID,B.FIRST_NAME||''||B.LAST_NAME
FROM EMPLOYEES A
INNER JOIN EMPLOYEES B
ON A.MANAGER_ID=B.EMPLOYEE_ID
ORDER BY 1;