--6-3 QUIZ

--1¹ø
SELECT *
FROM COVID19_TEST;

SELECT CONTINENT,
SUM(CASE WHEN QUARTER='1' THEN CASES ELSE 0 END) Q1,
SUM(CASE WHEN QUARTER='2' THEN CASES ELSE 0 END) Q2,
SUM(CASE WHEN QUARTER='3' THEN CASES ELSE 0 END) Q3,
SUM(CASE WHEN QUARTER='4' THEN CASES ELSE 0 END) Q4
FROM (SELECT TO_CHAR(DATES,'Q') QUARTER ,CONTINENT,NVL(SUM(NEW_CASES),0) CASES
        FROM COVID19_TEST
        WHERE 1=1
        AND TO_CHAR(DATES,'YYYY')='2020'
        AND CONTINENT IS NOT NULL
        GROUP BY TO_CHAR(DATES,'Q'),CONTINENT)
GROUP BY CONTINENT
ORDER BY 1;

--2¹ø
SELECT *
FROM PRODUCTS;
SELECT *
FROM ORDERS;

SELECT *
FROM ORDER_ITEMS;


SELECT SALE_YEAR,NVL(MODEL_2016,0) AS MODEL_2016,NVL(MODEL_2017,0) AS MODEL_2017,NVL(MODEL_2018,0) AS MODEL_2018
FROM (SELECT TO_CHAR(A.ORDER_DATE,'YYYY') SALE_YEAR,C.MODEL_YEAR, NVL(SUM(B.LIST_PRICE*B.QUANTITY),0) AMT
FROM ORDERS A, ORDER_ITEMS B, PRODUCTS C
WHERE A.ORDER_ID=B.ORDER_ID
AND B.PRODUCT_ID=C.PRODUCT_ID
GROUP BY TO_CHAR(A.ORDER_DATE,'YYYY'),C.MODEL_YEAR
)
PIVOT (SUM(AMT) FOR MODEL_YEAR IN ('2016' AS MODEL_2016 ,'2017' AS MODEL_2017,'2018' AS MODEL_2018))
ORDER BY SALE_YEAR;