--6-2 QUIZ
--1¹ø
SELECT *
FROM COVID19_TEST;

WITH COUN AS (SELECT COUNTRY, NVL(SUM(NEW_CASES),0) CASES FROM COVID19_TEST WHERE TO_CHAR(DATES,'YYYY')='2020' GROUP BY COUNTRY) 
SELECT *
FROM COUN
WHERE COUNTRY <> 'World'
ORDER BY 2 DESC
FETCH FIRST 5ROWS ONLY;

--2¹ø
SELECT *
FROM COVID19_TEST;


SELECT *
FROM ( SELECT COUNTRY,NVL(MAX(POPULATION),0) POPU,NVL(SUM(NEW_DEATHS),0) DEATH, DECODE(NVL(MAX(POPULATION),0),0,0,ROUND(NVL(SUM(NEW_DEATHS),0)/MAX(POPULATION)*100,5)) RATES
FROM COVID19_TEST
WHERE 1=1
AND TO_CHAR(DATES,'YYYY')='2020'
GROUP BY COUNTRY)
ORDER BY RATES DESC
FETCH FIRST 20 ROWS ONLY;