--4.1

--1번
SELECT COUNTRY_ID, COUNT(*)
FROM LOCATIONS
GROUP BY COUNTRY_ID;

--2번
SELECT *
FROM EMPLOYEES;

SELECT TO_CHAR(HIRE_DATE,'Q') 분기별,COUNT(*)
FROM EMPLOYEES
GROUP BY TO_CHAR(HIRE_DATE,'Q')
ORDER BY 분기별;

--3번
SELECT JOB_ID,ROUND(AVG(SALARY),0) AVG_SALARY, SUM(SALARY)/COUNT(EMPLOYEE_ID) AVG_SALARY_1
FROM EMPLOYEES
GROUP BY JOB_ID
ORDER BY 1;

--4번
SELECT *
FROM COVID19_TEST
WHERE ISO_CODE='KOR';

SELECT TO_CHAR(DATES,'YYYY-MM') 월별,SUM(NEW_CASES) 확진자수
FROM COVID19_TEST
WHERE ISO_CODE='KOR'
GROUP BY TO_CHAR(DATES,'YYYY-MM')
ORDER BY 1;

--5번
SELECT TO_CHAR(DATES,'YYYY-MM') MONTHS,SUM(NEW_CASES) 확진자수, NVL(SUM(NEW_DEATHS),0) 사망자수, 
CASE WHEN NVL(SUM(NEW_DEATHS),0)=0 THEN 0
ELSE ROUND(NVL(SUM(NEW_DEATHS)/SUM(NEW_CASES),0),2)
END AS 사망률
FROM COVID19_TEST
WHERE ISO_CODE='KOR'
GROUP BY TO_CHAR(DATES,'YYYY-MM')
ORDER BY 1;

--6번
SELECT ISO_CODE 국가, NVL(SUM(NEW_CASES),0) 확진자수
FROM COVID19_TEST
WHERE TO_CHAR(DATES,'YYYY-MM')='2020-10'
GROUP BY ISO_CODE
ORDER BY 2 DESC;

--4-2
--1번
SELECT JOB_ID, JOBS
FROM EMPLOYEES
WHERE DEPARTMENT_ID=60
UNION
SELECT JOB_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID=90
ORDER BY JOB_ID;
--SELECT 문에서 UNION을 사용할시 명시하는 컬럼 수, 데이터 타입은 동일하게 해야된다.

--2번
SELECT EMPLOYEE_ID,HIRE_DATE
FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE,'YYYY')='2001'
UNION
SELECT EMPLOYEE_ID,HIRE_DATE
FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE,'YYYY')='2003';

SELECT JOB_ID,SUM(SALARY)
FROM EMPLOYEES
GROUP BY JOB_ID
UNION
SELECT '합계',SUM(SALARY)
FROM EMPLOYEES
ORDER BY 1;

--4번
SELECT *
FROM covid19_test;
----------------------------
SELECT COUNTRY,TO_CHAR(DATES,'YYYY-MM'),SUM(NEW_CASES)
FROM covid19_test
WHERE TO_CHAR(DATES,'YYYY-MM') BETWEEN '2020-01' AND '2020-06'
GROUP BY COUNTRY, TO_CHAR(DATES,'YYYY-MM')
HAVING NVL(SUM(NEW_CASES),0)>=10000;
----------------------------
SELECT COUNTRY,TO_CHAR(DATES,'YYYY-MM'),SUM(NEW_CASES)
FROM covid19_test
WHERE TO_CHAR(DATES,'YYYY-MM') BETWEEN '2020-07' AND '2020-10'
GROUP BY COUNTRY, TO_CHAR(DATES,'YYYY-MM')
HAVING NVL(SUM(NEW_CASES),0)<=1000;
---------------------------------
SELECT COUNTRY
FROM covid19_test
WHERE TO_CHAR(DATES,'YYYY-MM') BETWEEN '2020-01' AND '2020-06'
GROUP BY COUNTRY, TO_CHAR(DATES,'YYYY-MM')
HAVING NVL(SUM(NEW_CASES),0)>=10000
INTERSECT
SELECT COUNTRY
FROM covid19_test
WHERE TO_CHAR(DATES,'YYYY-MM') BETWEEN '2020-07' AND '2020-10'
GROUP BY COUNTRY, TO_CHAR(DATES,'YYYY-MM')
HAVING NVL(SUM(NEW_CASES),0)<=1000;

--SELECT에서  TO_CHAR(DATES,'YYYY-MM'),SUM(NEW_CASES) 넣으면 왜 안되지?
-- 나라, 월별 확진일, 확진수가 INTERSECT를 사용하면 다 같은 값을 조회하는데 없기때문에!
