
--SELECT문

/*SELECT 컬럼~
FROM 테이블명
WHERE 조건
ORDER BY 정렬순서;*/

DESC EMPLOYEES;

SELECT *
FROM DEPARTMENTS;

--100번인 사원 조회
SELECT *
FROM EMPLOYEES
WHERE employee_id = 100;

--100번이 아닌 사원 조회
SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID <>100; 

--100번이 아닌 사원 조회
SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID !=100; 

--사번이 100보다 크고 JOB_ID가 ST_CLERK인 사원조회
SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID >100 AND JOB_ID='ST_CLERK';

--급여가 5000이상이 사원 조회
SELECT *
FROM EMPLOYEES
WHERE SALARY>=5000;

--급여가 5000이상인 사원의 사번과 이름 급여를 조회
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY
FROM EMPLOYEES
WHERE SALARY>=5000;

--ORDER BY 
--사번순으로 정렬
SELECT *
FROM EMPLOYEES
ORDER BY EMPLOYEE_ID;

--사번순으로 내림차순 정렬
SELECT *
FROM EMPLOYEES
ORDER BY EMPLOYEE_ID DESC;

--이름 성순으로 오름차순 정렬
SELECT *
FROM EMPLOYEES
ORDER BY FIRST_NAME, LAST_NAME;

--이름 오름차순, 성 내림차순 정렬

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME
FROM EMPLOYEES
ORDER BY FIRST_NAME,LAST_NAME DESC;

--사원의 사번과 이름, 급여를 급여가 5000이상인 급여가 높은 순서로 조회
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY>=5000
ORDER BY SALARY DESC;

--숫자를 명시해서 정렬 가능함
SELECT *
FROM EMPLOYEES;

SELECT *
FROM EMPLOYEES
ORDER BY 2,3 DESC; --2번째와 3번째 열을 중심으로 정렬

--ORDER_BY NULL정렬 방법 1) NULLS FIRST 2)NULLS LAST

SELECT EMPLOYEE_ID, FIRST_NAME,LAST_NAME,COMMISSION_PCT
FROM EMPLOYEES
ORDER BY COMMISSION_PCT NULLS FIRST;

--SQL 연산자
SELECT 1+1 PLUS_TEST, 1-1 MINUS_TEST
FROM DUAL;

--SQL 문자열 결합 1
SELECT 'A' || 'B' ||  'C'
FROM DUAL;

--SQL 문자열 결합 2
SELECT 'A' || '-' || 'B' || '-' || 'C'
FROM DUAL;

--SQL 비교 연산자
SELECT *
FROM EMPLOYEES
WHERE SALARY BETWEEN 3000 AND 5000
ORDER BY SALARY;

--SQL 비교 연산자
SELECT *
FROM EMPLOYEES
WHERE NOT(SALARY=2500)
ORDER BY SALARY;

--SQL 기타 연산자
    /* 
    (IS NULL, IS NOT NULL)
    LIKE '%D'
    LIKE 'D%'
    LIKE '%D%'
    컬럼I IN ( 값123)
    */
SELECT *
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NULL;

SELECT *
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL;

SELECT *
FROM EMPLOYEES
WHERE PHONE_NUMBER LIKE '011%';

SELECT *
FROM EMPLOYEES
WHERE PHONE_NUMBER LIKE '%124%';

SELECT *
FROM EMPLOYEES
WHERE JOB_ID IN ('IT_PROG','AD_VP','FI_ACCOUNT');

SELECT *
FROM EMPLOYEES
WHERE JOB_ID NOT IN ('IT_PROG','AD_VP','FI_ACCOUNT');

--CASE문 단순형, 검색형

SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY,JOB_ID
    ,CASE WHEN SALARY BETWEEN 1 AND 5000 THEN '낮음'
          WHEN SALARY BETWEEN 5001 AND 10000 THEN '중간'
           WHEN SALARY BETWEEN 10000 AND 15000 THEN '높음'
           ELSE '최상위'
           END SALARY_RANK
    FROM EMPLOYEES;
    
    2-1

--2번 
CREATE TABLE COUNTRY_TEST( COUNTRY_ID NUMBER NOT NULL PRIMARY KEY, COUNTRY_NAME VARCHAR2(100) NOT NULL);

--3번 
ALTER TABLE COUNTRY_TEST ADD REGION_ID NUMBER NULL; DESC COUNTRY_TEST;

--4번 
ALTER TABLE COUNTRY_TEST MODIFY REGION_ID NUMBER NOT NULL DESC COUNTRY_TEST;

--5번 
DROP TABLE COUNTRY_TEST;

--2-2

--5번 
SELECT * FROM LOCATIONS WHERE (LOCATION_ID>=2000 AND LOCATION_ID<3000);

--6번 
SELECT * FROM EMPLOYEES;

SELECT * FROM EMPLOYEES WHERE FIRST_NAME = 'David' AND SALARY>=6000;

SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID=80;

SELECT * FROM LOCATIONS WHERE LOCATION_ID=2500;

--2-3 --1번
SELECT * FROM EMPLOYEES WHERE MANAGER_ID IS NULL;

--2번 
DESC EMPLOYEES;

SELECT COMMISSION_PCT, SALARY 
,CASE WHEN COMMISSION_PCT IS NULL THEN SALARY
      ELSE SALARY+(SALARY*COMMISSION_PCT)
      END SALARY2
      FROM EMPLOYEES;

--3번 
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME 
FROM EMPLOYEES 
WHERE ROWNUM<1;

--4번
DESC LOCATIONS;

SELECT CITY 
FROM LOCATIONS 
WHERE CITY LIKE 'S%';

--5번 
SELECT * FROM LOCATIONS;

SELECT POSTAL_CODE || ' - ' || STREET_ADDRESS || ' - ' || CITY ||' - '|| STATE_PROVINCE ||' - '|| COUNTRY_ID AS 주소 
FROM LOCATIONS 
WHERE COUNTRY_ID='US';

--6번 
SELECT POSTAL_CODE ||' - '|| STREET_ADDRESS ||' - '|| CITY ||' - '|| STATE_PROVINCE ||' - '|| COUNTRY_ID AS 주소 
FROM LOCATIONS 
WHERE COUNTRY_ID='UK' 
AND POSTAL_CODE IS NOT NULL 
ORDER BY 1;

--7번 
SELECT 
CASE WHEN POSTAL_CODE IS NULL THEN '99999'
ELSE POSTAL_CODE
END ||'-'||STREET_ADDRESS||'-'||CITY||'-'||STATE_PROVINCE||'-'||COUNTRY_ID AS 주소
FROM LOCATIONS 
WHERE COUNTRY_ID='UK'
ORDER BY 1;
